Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.bucket} # Getting the name of table I defined under custom in serverless.yml
  # Make Bucket publicly accessable
  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
        Bucket: !Ref Bucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: '*' # public access to access the bucket files 
              Action: s3:GetObject
              Resource: 'arn:aws:s3:::${self:custom.bucket}/*'
     